### ISSUE TITLE
babel-node dependency

### ISSUE THREAD

**Issue by sebs** [jordanell/testing-with-sequelize#1]
This seems odd, there is a error emssage regarding this on node 9.11.2

It refers to another babel package. It seems, you are not using the lates version of babel.

**Comment by jordanell** [comment]
Upgraded all dependencies and moved to node `10.13.0` here https://github.com/jordanell/testing-with-sequelize/commit/91922892e9ab29be2d96449408bf836f352ab576 and here https://github.com/jordanell/testing-with-sequelize/commit/b14f766019a583f5fdfbf8b26c0365a32f4dff0e. 

I was unable to reproduce any errors regarding node `9.11.2` however, so I am closing this issue.

**Comment by sebs** [comment]
ty, will move to 10 as well
